title: Natthakit Singhanatkaisi  # You can add your name here

# logo: my-profile.png # Use a relative path to logo image 

description: My first CV

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: natthakit.sin@dome.tu.ac.th # 
